apiVersion: v1
kind: Service
metadata:
  name: gitlab-https
spec:
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-http
spec:
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
spec:
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 22
      nodePort: 30222
  type: NodePort
