apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-pull-mistral
  namespace: ollama
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: curl
          image: curlimages/curl:latest
          command:
            - "sh"
            - "-c"
            - >
              curl -v -X POST http://ollama:11434/api/pull
              -d '{"name":"mixtral:8x7b"}'
