apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'oci://ghcr.io/actions/actions-runner-controller-charts'
    chart: gha-runner-scale-set-controller
    targetRevision: 0.9.3
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
