apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://danmanners.github.io/gha-scale-set-helm'
    chart: gha-runner-scale-set-controller
    targetRevision: 0.9.0
    helm:
      values: |
        crds:
          install: true
          annotations: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
