apiVersion: v1
kind: Service
metadata:
  name: meeting-plus
  namespace: default
  labels:
    app: meeting-plus
spec:
  selector:
    app: meeting-plus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP