apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mael-app/infra-k8s.git
    targetRevision: main
    path: manifests/github-runner
    helm:
      valueFiles:
        - github-runner-controller-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
