apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mael-app/infra-k8s.git'
    targetRevision: main
    path: manifests/github-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner-controller-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
