apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://danmanners.github.io/gha-scale-set-helm'
    chart: gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      values: |
        githubConfigUrl: "https://github.com/HSMM-Epitech/zappy"
        githubConfigSecret: "gh-secret"
        minRunners: 1
        maxRunners: 3
        runnerGroup: "default"
        runnerLabels:
          - "self-hosted"
          - "k8s"
        template:
          spec:
            containers:
            - name: runner
              image: ghcr.io/actions/actions-runner:latest
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "2Gi"
                  cpu: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
