apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: onerahmet/openai-whisper-asr-webservice:latest
        ports:
        - containerPort: 9000
        env:
        - name: ASR_ENGINE
          value: openai_whisper
        - name: ASR_MODEL
          value: base        # tiny, base, small, medium, large-v3
        - name: ASR_DEVICE
          value: cpu       
        - name: MODEL_IDLE_TIMEOUT
          value: "0"       
        resources:
          requests:
            cpu: "2000m"
            memory: "8Gi"
          limits:
            cpu: "8000m"
            memory: "24Gi"